### ISSUE TITLE
Register autoloader for proxies to avoid issues when unserializing

### ISSUE THREAD

**Issue by ikwattro** [neo4j-php/neo4j-symfony#31]
Issue opened as reminder

References : 

https://github.com/graphaware/neo4j-php-ogm/issues/122

https://github.com/symfony/symfony/issues/3907

https://github.com/doctrine/DoctrineMongoDBBundle/pull/85

https://github.com/ikwattro/neo4j-ogm-symfony-security/commit/b7a85818733454aff9c9a3efcbbf0c5ad0557bd3

**Comment by Nyholm** [comment]
Thank you

**Comment by theUm** [comment]
Hi. I wrote doctrine-like proxy class autoloader. It tryes to load proxy class from cache (separate dir for each entity manager) and if class is not present - triggers its creation. 
Also neo4j bundle clears all entity managers and closes all connections on shutdown.
[https://github.com/neo4j-contrib/neo4j-symfony/pull/35](https://github.com/neo4j-contrib/neo4j-symfony/pull/35)

P.S. plz fix tests - it seems that test env cant connect to neo4j via `bolt://localhost:7687`
