### ISSUE TITLE
Up-to-date package versions

### ISSUE THREAD

**Issue by shaedrich** [neo4j-php/neo4j-symfony#76]
Will there be up-to-date package versions (like PHP 8) in composer.json any time soon? I tried to install it with my pre-existing Laravel installation, but it turns out to be impossible even with downgrading other packages, which in itself is already annoying.

**Comment by transistive** [comment]
Hi @shaedrich,

Thanks for reaching out. I just managed to get higher privileges into the repository, so I could merge my PR. I took the liberty to fix your issue as well.

**Comment by shaedrich** [comment]
Hi @transistive,

Thanks for the fix! That sure helps a lot.
